#ifndef CONFIGURATION_CONFIG_H_
#define CONFIGURATION_CONFIG_H_

#define FILE_NAME_LENGTH 100
#define ARRAY_SIZE 100000000
#define STDIN "100_000_000.bin"
#define BOOL_PARALLEL 0
#define BASE_THREAD_CNT 10

#endif // CONFIGURATION_CONFIG_H_