dist: trusty 
sudo: required

language: c

os:
  - linux
compiler: 
  - gcc
addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck
before_script:
  - cd hw_2
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cmake .
  - make

script:
  - valgrind --track-origins=yes --leak-check=full ./test_naive
  - valgrind --track-origins=yes --leak-check=full ./test_parallel
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./parallel 
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./sequential 
  - ./stress
  - cd hw_2
after_success:
  - bash <(curl -s https://codecov.io/bash)
